version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    rebase-strategy: "disabled"

  - package-ecosystem: github-actions
    directory: .github/actions/upload-coverage/
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    rebase-strategy: "disabled"
