version: 2

updates:
- package-ecosystem: pip
  directory: "/install"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  rebase-strategy: "disabled"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  rebase-strategy: "disabled"
