version: 2

updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    rebase-strategy: "disabled"
    groups:
      actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: .github/actions/upload-coverage/
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    rebase-strategy: "disabled"
    groups:
      actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7
