# Derived from <https://github.com/pyca/cryptography/blob/SOME_REF/.github/actions/upload-coverage/action.yml>
# Originally authored by the PyCA Cryptography maintainers, and licensed under
# the terms of the BSD license:
# <https://github.com/pyca/cryptography/blob/main/LICENSE.BSD>

name: Upload Coverage
description: Upload coverage files

runs:
  using: "composite"

  steps:
    # FIXME(jl): codecov has the option of including machine information in filename that would solve this unique naming
    # issue more completely.
    - run: |
        COVERAGE_UUID=$(python3 -c "import uuid; print(uuid.uuid4())")
        echo "COVERAGE_UUID=${COVERAGE_UUID}" >> $GITHUB_OUTPUT
        if [ -f .coverage ]; then
          mv .coverage .coverage.${COVERAGE_UUID}
        fi
      id: coverage-uuid
      shell: bash
    - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: coverage-data-${{ steps.coverage-uuid.outputs.COVERAGE_UUID }}
        include-hidden-files: 'true'
        path: |
          .coverage.*
          *.lcov
        if-no-files-found: ignore
